export const responseMessage = {
  fetchedMovies: 'Fetched all movies successfully.',
  searchedMovies: 'Fetched all searched movies successfully.',
  fetchedMovie: 'Fetch movie successfully.',
  addedMovie: 'Added movie successfully.',
  updatedMovie: 'Updated movie successfully.',
  deletedMovie: 'Deleted movie successfully.',
  registered: 'Registered successfully.',
  loggedin: 'Loggedin successfully.',
  getCurrentUser: 'Get profile successfully.',
  addedUser: 'Added user successfully.',
  fetchedUsers: 'Fetched all users successfully.',
  fetchedUser: 'Fetch user successfully.',
  updatedUser: 'Updated user successfully.',
  deletedUser: 'Deleted user successfully.',
};
