export const responseMessage = {
  fetchedMovies: 'Fetched all movies successfully.',
  searchedMovies: 'Searched movies successfully.',
  fetchedMovie: 'Fetch movie successfully.',
  addedMovie: 'Added movie successfully.',
  updatedMovie: 'Updated movie successfully.',
  deletedMovie: 'Deleted movie successfully.',
  registered: 'Registered successfully.',
  loggedin: 'Loggedin successfully.',
  getCurrentUser: 'Get profile successfully.',
  addedUser: 'Added user successfully.',
  fetchedUsers: 'Fetched all users successfully.',
  fetchedUser: 'Fetch user successfully.',
  updatedUser: 'Updated user successfully.',
  deletedUser: 'Deleted user successfully.',
  searchedUsers: 'Searched users successfully.',
  addedActor: 'Added actor successfully.',
  fetchedActors: 'Fetched all actors successfully.',
  fetchedActor: 'Fetch actor successfully.',
  updatedActor: 'Updated actor successfully.',
  deletedActor: 'Deleted actor successfully.',
  addedReview: 'Added review successfully.',
  fetchedReviews: 'Fetched all reviews successfully.',
  fetchedReview: 'Fetch review successfully.',
  updatedReview: 'Updated review successfully.',
};
